# Generated by Django 2.2 on 2021-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=30)),
                ('car_moddel', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
            ],
        ),
    ]
