# Generated by Django 2.2 on 2021-10-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='car_moddel',
            new_name='car_model',
        ),
    ]
