# Generated by Django 2.2 on 2021-10-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211008_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='car_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
