# Generated by Django 2.2 on 2021-10-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cardetails_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='car_image',
            new_name='front_image',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='interior_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='rear_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='side_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
