# Generated by Django 2.2 on 2021-10-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211008_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='carImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('rear_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('interior_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='front_image',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='interior_image',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='rear_image',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='side_image',
        ),
    ]
