# Generated by Django 2.2 on 2021-10-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211012_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carImages',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
