# Generated by Django 2.2 on 2021-10-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211013_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='rear_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
